### PR TITLE
fix: only render image when source is avaible, tidy up layout

### LINKED ISSUE #124: Placeholder image for Mentor card not found
### Describe the bug

https://tupu-app.netlify.app/mentors/rec_c8ei3pl17c4fhhvh13kg

image

### PR DESCRIPTION
**Pull request by maranta1**
### What Github issue does this PR relate to?

Close #124 

Changes proposed in this pull request:

- only render image on mentor profile page if the image is available
- simplify the page layout

Screenshot 2023-04-02 at 16 15 59

Screenshot 2023-04-02 at 16 16 08

### Quality Assurance(QA) Checklist

- [x] The app builds and runs properly

### CODE REVIEW

File: pages/mentors/[id].js [hunk 1]
```diff
@@ -52,26 +50,23 @@ export default function MentorPage() {
...
+          <Heading color="gray.700">
+            {data.name}
+          </Heading>
+          {data.title &&
             <Heading size="md" color="gray.500">
               {data.title}
             </Heading>
-            <Stack direction={"row"} justifyContent={"left"}>
+          }
+          {data.twitter || data.linkedin &&
```
Comment (lorepirri) [inline pages/mentors/[id].js:68]: somehow the condition must be enclosed in parenthesis otherwise it won't render (e.g. https://deploy-preview-126--tupu-app.netlify.app/mentors/rec_c8ei3pt17c43qguaejsg )

```suggestion
          {(data.twitter || data.linkedin) &&
```

---

image

**Review by lorepirri — CHANGES_REQUESTED** [review]
looks good! One small thing about the block for linkedin/twitter

**Review by lorepirri — APPROVED** [review]
Once fixed the parenthesis is good to go
